version: '3.3'
services:
  futsal-planner-db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: futsal-planner
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  futsal-planner-front:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    working_dir: /myapp
    ports:
      - "${FRONT_PORT}:3000"
    links:
      - futsal-planner-db
    depends_on:
      - futsal-planner-db
    labels:
      - "traefik.enable=true"
      - "traefik.backend=front-${COMPOSE_PROJECT_NAME}"
      - "traefik.frontend.rule=Host:${FRONT_HOST}.{domain}"
      - "traefik.port=${FRONT_PORT}"
      - "traefik.docker.network=${FRONT_PROXY}"
    environment:
      RAILS_ENV: "${RAILS_ENV}"
    networks:
      - default
      - traefik_proxy
networks:
  traefik_proxy:
    external: true
